id = "kirby-content"
name = "Kirby Content"
description = "Syntax highlighting for Kirby CMS content files"
version = "0.1.0"
schema_version = 1
authors = ["Thomas Günther <mail@medienbaecker.com>"]
repository = "https://github.com/medienbaecker/zed-kirby-content"

[grammars.kirby_content]
repository = "https://github.com/medienbaecker/tree-sitter-kirby-content"
rev = "07beb8b482be95bdd47e09defd767bc03d0b0599"
